"""Categorized Turkish word bank with harder clues."""

REVEAL_INTERVAL_SECONDS = 7
POINTS_PER_HIDDEN_LETTER = 10
TOTAL_QUESTIONS = 8

CATEGORIES: dict[str, dict] = \
{'bilim': {'label': 'Bilim',
           'description': 'Fizik, kimya, biyoloji ve teknoloji',
           'words_by_length': {3: [{'word': 'AÇI', 'hint': 'Sinüs ve kosinüsle ölçülen geometrik değer'},
                                   {'word': 'GEN', 'hint': "Mendel'in bezelyelerinde aradığı kalıtım birimi"},
                                   {'word': 'DNA', 'hint': 'Çift sarmal yapıdaki kalıtım molekülü'},
                                   {'word': 'IŞI', 'hint': 'c·λ ile ilişkilendirilen enerji taşıyıcısı'},
                                   {'word': 'TIP', 'hint': 'Tıp fakültesinden mezun olan kişi'},
                                   {'word': 'AZO', 'hint': 'N₂ ile ilgili bileşik grubunun adı'}],
                               4: [{'word': 'İYON', 'hint': 'Elektron alışverişi sonrası yüklenen tanecik'},
                                   {'word': 'ATOM', 'hint': 'Periyodik tablodaki en küçük birim'},
                                   {'word': 'ASIT', 'hint': "pH ölçeğinde 7'nin altında kalan madde"},
                                   {'word': 'AMİP', 'hint': 'Tek hücreli, hareketli protist'},
                                   {'word': 'ASAL', 'hint': 'Yalnızca 1 ve kendisine bölünebilen sayı'},
                                   {'word': 'İYOT', 'hint': 'Halojenler grubunda, mor buharlı element'}],
                               5: [{'word': 'FOTON', 'hint': 'Işığın kuantize enerji paketi'},
                                   {'word': 'VİRÜS', 'hint': 'Konak olmadan çoğalamayan patojen'},
                                   {'word': 'ENZİM', 'hint': 'Biyokimyasal tepkimeyi hızlandıran katalizör'},
                                   {'word': 'OKSİT', 'hint': 'Metal ile oksijenin birleşiminden doğan bileşik'},
                                   {'word': 'METAN', 'hint': 'Doğal gazın ana bileşeni, CH₄'},
                                   {'word': 'OKTAV', 'hint': 'Frekansın iki katına çıktığı aralık'}],
                               6: [{'word': 'PROTON', 'hint': 'Atom çekirdeğinde pozitif yüklü parçacık'},
                                   {'word': 'NÖTRON', 'hint': 'Çekirdekte yüksüz ağırlık merkezi'},
                                   {'word': 'İSOTOP', 'hint': 'Aynı proton sayısı, farklı kütle numarası'},
                                   {'word': 'GRAFİT', 'hint': 'Kurşun kalemin ucundaki karbon formu'},
                                   {'word': 'FİZYON', 'hint': 'Çekirdeğin bölünmesiyle enerji açığa çıkması'},
                                   {'word': 'FÜZYON', 'hint': 'Güneşin enerji üretimindeki birleşme süreci'}],
                               7: [{'word': 'PROTEİN', 'hint': 'Amino asit zincirlerinden oluşan makromolekül'},
                                   {'word': 'GRAVİTE', 'hint': "Newton'un elma hikâyesindeki çekim kuvveti"},
                                   {'word': 'ANTİJEN', 'hint': 'Bağışıklık sistemini uyaran yabancı madde'},
                                   {'word': 'DİNAMİK', 'hint': 'Hareketin nedenlerini inceleyen fizik dalı'},
                                   {'word': 'ELEMENT', 'hint': 'Periyodik tablodaki saf madde birimi'},
                                   {'word': 'MOLEKÜL', 'hint': 'İki veya daha fazla atomun bağlandığı birim'}],
                               8: [{'word': 'ELEKTRİK', 'hint': 'Ampulü yakan, fırtınada çakan enerji'},
                                   {'word': 'MANYETİK', 'hint': 'Demir tozlarını kendine çeken alan özelliği'},
                                   {'word': 'ORGANİZM', 'hint': 'Canlılık gösteren bütün varlık'},
                                   {'word': 'KROMOZOM', 'hint': 'Genlerin sıralandığı yapı'},
                                   {'word': 'BİLİMSEL', 'hint': 'Deney ve kanıta dayanan yöntem'},
                                   {'word': 'HIZLANMA', 'hint': 'Hızın zamana göre değişim oranı'}],
                               9: [{'word': 'MİKROSKOP', 'hint': 'Gözle görülemeyeni büyüten optik alet'},
                                   {'word': 'RADYASYON', 'hint': "Çernobil'de yayılan görünmez tehlike"},
                                   {'word': 'MATEMATİK', 'hint': 'İspat ve ispat arasındaki disiplin'},
                                   {'word': 'HİPOTENÜS', 'hint': 'Dik üçgende 90° karşısındaki kenar'}]},
           'bonus': [{'word': 'FOTOSENTEZ', 'hint': "Klorofilin ışıkla CO₂'yi şekere dönüştürmesi"},
                     {'word': 'ANTROPOLOJİ', 'hint': "Homo sapiens'in kültürünü inceleyen bilim"},
                     {'word': 'BİLİNÇALTI', 'hint': "Freud'un buzdağının su altı katmanı"},
                     {'word': 'BAKTERİYOLOJİ', 'hint': "Pasteur'ün mikroskopta incelediği canlılar bilimi"},
                     {'word': 'ELEKTROMANYETİK', 'hint': 'Maxwell denklemlerinin tanımladığı birleşik alan'},
                     {'word': 'PSİKOLOJİST', 'hint': 'Rorschach testini uygulayabilen uzman'}]},
 'tarih': {'label': 'Tarih',
           'description': 'Uygarlıklar, savaşlar ve coğrafya',
           'words_by_length': {3: [{'word': 'TÜR', 'hint': 'Oğuz boylarının ortak adlandırması'},
                                   {'word': 'KÖK', 'hint': 'Soy ağacında yukarı çıkıldığında varılan nokta'},
                                   {'word': 'ASK', 'hint': 'Orduya katılan silahlı er'},
                                   {'word': 'TUZ', 'hint': "İpek Yolu'nda değerli takas malı"},
                                   {'word': 'GÖÇ', 'hint': 'Konar göçerlerin mevsimlik hareketi'},
                                   {'word': 'SUR', 'hint': 'Kaleyi çevreleyen taş duvar'}],
                               4: [{'word': 'ORDU', 'hint': "Fatih'in fetihlerinde yürüttüğü güç"},
                                   {'word': 'TAHT', 'hint': 'Padişahın oturduğu, miras kavgası çıkaran yer'},
                                   {'word': 'TAPU', 'hint': "Osmanlı'da toprağın mülkiyet belgesi"},
                                   {'word': 'KALE', 'hint': 'Kuşatmalarda son direniş noktası'},
                                   {'word': 'ANIT', 'hint': 'Geçmişi yaşatmak için dikilen taş yapı'},
                                   {'word': 'VAKF', 'hint': "Osmanlı'da hayır kurumlarının hukuki çatısı"}],
                               5: [{'word': 'TİMAR', 'hint': "Osmanlı'da sipahiye verilen gelir toprağı"},
                                   {'word': 'VAKIF', 'hint': 'Hayır işleri için ayrılan mülk sistemi'},
                                   {'word': 'FATİH', 'hint': "1453'te Konstantinopolis'i alan padişah"},
                                   {'word': 'PRENS', 'hint': 'Taht varisi olabilecek soylu erkek'},
                                   {'word': 'SAVAŞ', 'hint': 'Barış antlaşmasıyla sona eren çatışma'}],
                               6: [{'word': 'KERVAN', 'hint': "İpek Yolu'nda develerle ilerleyen ticaret grubu"},
                                   {'word': 'SULTAN', 'hint': 'Osmanlı tahtında oturan unvan'},
                                   {'word': 'GÖÇEBE', 'hint': 'Konar göçer yaşam süren topluluk'},
                                   {'word': 'ORDUSU', 'hint': 'Padişahın emrindeki askerî güç'},
                                   {'word': 'PRENSİ', 'hint': 'Tahtın genç varisi'},
                                   {'word': 'TİMARI', 'hint': 'Sipahiye verilen toprak geliri'}],
                               7: [{'word': 'OSMANLI', 'hint': "1299'da kurulan imparatorluk"},
                                   {'word': 'YUNANLI', 'hint': 'Antik felsefenin doğduğu halk'},
                                   {'word': 'SARAYLI', 'hint': 'Harem ve divanda görev yapan kişi'},
                                   {'word': 'TAPINAK', 'hint': 'Kutsal ayinlerin yapıldığı ibadet yapısı'},
                                   {'word': 'ANTALYA', 'hint': 'Akdeniz kıyısındaki antik Attaleia'},
                                   {'word': 'FETİHÇİ', 'hint': 'Surları aşarak şehir alan komutan'}],
                               8: [{'word': 'İSTANBUL', 'hint': "1453'ten sonra fethedilen metropol"},
                                   {'word': 'YARIMADA', 'hint': 'Üç tarafı denizle çevrili kara parçası'},
                                   {'word': 'SICAKLIK', 'hint': 'Termometreyle ölçülen iklim değeri'},
                                   {'word': 'PASAPORT', 'hint': 'Sınır geçişinde sorulan resmî belge'},
                                   {'word': 'PERŞEMBE', 'hint': "Haftanın Cuma'dan önceki günü"},
                                   {'word': 'ÇARŞAMBA', 'hint': 'Haftanın ortasına yakın günü'}],
                               9: [{'word': 'KARADENİZ', 'hint': "Türkiye'nin kuzeyindeki iç deniz"},
                                   {'word': 'PAZARTESİ', 'hint': 'Haftanın ilk iş günü'},
                                   {'word': 'CUMARTESİ', 'hint': 'Hafta sonunun ilk günü'},
                                   {'word': 'DEMOKRASİ', 'hint': 'Halk egemenliğine dayanan yönetim'},
                                   {'word': 'ASTRONOMİ', 'hint': 'Gök cisimlerini inceleyen bilim'},
                                   {'word': 'ARKEOLOJİ', 'hint': 'Kazı ile geçmişi ortaya çıkaran bilim'}]},
           'bonus': [{'word': 'KONSTANTİNOPOLİS', 'hint': "Bizans'ın başkenti, 1453'te düştü"},
                     {'word': 'MİLLİMÜCADELE', 'hint': "1919'da başlayan bağımsızlık savaşı"},
                     {'word': 'LOZANANTLAŞMASI', 'hint': "1923'te imzalanan barış belgesi"},
                     {'word': 'OSMANLIİMPARATORLUĞU', 'hint': '1299-1922 arası Türk devleti'},
                     {'word': 'SELÇUKLULAR', 'hint': '1071 Malazgirt zaferinin sahibi'},
                     {'word': 'ANADOLUBİRLİĞİ', 'hint': 'Moğol baskısı sonrası kurulan beylikler'}]},
 'kultur': {'label': 'Kültür',
            'description': 'Edebiyat, sanat ve müzik',
            'words_by_length': {3: [{'word': 'Şİİ', 'hint': 'Hece ve aruzla kurulan edebî tür'},
                                    {'word': 'NAZ', 'hint': 'Gazeldeki dize bölümü'},
                                    {'word': 'TEM', 'hint': 'Bestenin ana melodik fikri'},
                                    {'word': 'ROL', 'hint': 'Oyuncunun sahnede canlandırdığı karakter'},
                                    {'word': 'AHA', 'hint': 'Klasik Türk müziğinde makam adı'},
                                    {'word': 'EZO', 'hint': 'Anadolu ezgilerinde sık geçen kadın adı'}],
                                4: [{'word': 'DEST', 'hint': 'Epik anlatının uzun türü'},
                                    {'word': 'UYAK', 'hint': 'Şiirdeki ses benzerliği düzeni'},
                                    {'word': 'ARUZ', 'hint': 'Divân edebiyatının vezin sistemi'},
                                    {'word': 'NOTA', 'hint': 'Müzikte sesin yazıya dökülmüş hali'},
                                    {'word': 'DİZE', 'hint': 'Şiirin tek satırlık birimi'}],
                                5: [{'word': 'GİRİŞ', 'hint': 'Roman ve makalenin açılış bölümü'},
                                    {'word': 'MAKAM', 'hint': 'Türk müziğinde melodi dizisi'},
                                    {'word': 'METİN', 'hint': 'Sahnedeki oyuncunun söyledikleri'},
                                    {'word': 'KİTAP', 'hint': 'Cilt, sayfa ve kapaktan oluşan eser'}],
                                6: [{'word': 'HEYKEL', 'hint': "Rodin'in düşünen adamı gibi üç boyutlu sanat"},
                                    {'word': 'KONSER', 'hint': 'Canlı icra dinlenen müzik etkinliği'},
                                    {'word': 'POSTER', 'hint': 'Film afişi olarak duvara asılan görsel'},
                                    {'word': 'OYUNCU', 'hint': 'Sahne veya sette rol alan sanatçı'},
                                    {'word': 'MİSAİR', 'hint': 'Antik piramitlerin bulunduğu ülke'}],
                                7: [{'word': 'ROMANCI', 'hint': 'Uzun anlatı yazan edebiyatçı'},
                                    {'word': 'FRAGMAN', 'hint': 'Sinemada film öncesi gösterilen tanıtım'},
                                    {'word': 'ŞAİRANE', 'hint': 'Şiire yakışır, duygusal üslup'},
                                    {'word': 'MAKAMCI', 'hint': 'Klasik Türk müziğinde makam bilgini'},
                                    {'word': 'KONSERİ', 'hint': 'Salonda dinlenen canlı müzik etkinliği'},
                                    {'word': 'SAHNELİ', 'hint': 'Perde ve seyirci gerektiren gösteri'}],
                                8: [{'word': 'FOTOĞRAF', 'hint': 'Işıkla yakalanan donmuş an'},
                                    {'word': 'YÖNETMEN', 'hint': 'Filmin görsel anlatımından sorumlu kişi'},
                                    {'word': 'FİLOLOJİ', 'hint': 'Dilleri inceleyen bilim dalı'},
                                    {'word': 'MÜZİSYEN', 'hint': 'Enstrüman çalan profesyonel sanatçı'},
                                    {'word': 'ELEŞTİRİ', 'hint': 'Eserin niteliğini değerlendiren yazı'},
                                    {'word': 'MANTIKLI', 'hint': 'Tutarlı düşünce zinciri'}],
                                9: [{'word': 'KÜTÜPHANE', 'hint': 'Kitapların korunduğu sessiz mekân'},
                                    {'word': 'PSİKOLOJİ', 'hint': 'Zihinsel süreçleri inceleyen bilim'},
                                    {'word': 'DEKORATÖR', 'hint': 'Sahne ve set düzenleyen sanatçı'},
                                    {'word': 'SERAMİKÇI', 'hint': 'Kilden kap ve heykel yapan zanaatkâr'}]},
            'bonus': [{'word': 'FOTOĞRAFÇILIK', 'hint': 'Işık ve gölgeyle an yakalama sanatı'},
                      {'word': 'ELEŞTİRMEN', 'hint': 'Eserleri değerlendiren yazın adamı'},
                      {'word': 'TRANSPOSİZYON', 'hint': 'Müzikte ezgiyi başka tona taşıma'},
                      {'word': 'EXISTANSİYALİZM', 'hint': "Sartre'ın varoluşçu felsefesi"}]},
 'doga': {'label': 'Doğa',
          'description': 'Bitkiler, hayvanlar ve doğa olayları',
          'words_by_length': {3: [{'word': 'KIŞ', 'hint': 'Kar yağışının baskın olduğu mevsim'},
                                  {'word': 'YAZ', 'hint': 'Gündönümüne en yakın sıcak mevsim'},
                                  {'word': 'ÇIĞ', 'hint': 'Dağ yamacından kopan kar kütlesi'},
                                  {'word': 'GÖL', 'hint': 'Kara içinde kapalı su kütlesi'},
                                  {'word': 'DAĞ', 'hint': 'Yüksek arazi formu'},
                                  {'word': 'NEM', 'hint': 'Havadaki su buharı oranı'}],
                              4: [{'word': 'KURT', 'hint': 'Masallardaki yabani köpek türü'},
                                  {'word': 'KART', 'hint': 'Yırtıcı kuş familyasının büyük üyesi'},
                                  {'word': 'OVAJ', 'hint': 'Yamaçtan aşağı kayan toprak kütlesi'},
                                  {'word': 'AĞAÇ', 'hint': 'Odun dokulu, gövdeli bitki'},
                                  {'word': 'YUNU', 'hint': 'Koyundan elde edilen lif'}],
                              5: [{'word': 'KUNDU', 'hint': 'Ormanlarda yaşayan, misk salgılayan hayvan'},
                                  {'word': 'SELVİ', 'hint': 'Uzun boylu, ince yapraklı ağaç'},
                                  {'word': 'YILKI', 'hint': 'Vahşi doğada yetişen at sürüsü'},
                                  {'word': 'ASLAN', 'hint': 'Ormanların kralı olarak anılan yırtıcı'},
                                  {'word': 'AKREP', 'hint': 'Çöl ve kayalıklarda yaşayan zehirli sürüngen'},
                                  {'word': 'ÇAKAL', 'hint': 'Leşle beslenen, uluyan yırtıcı'}],
                              6: [{'word': 'BAYKUŞ', 'hint': 'Gece avlanan, büyük gözlü kuş'},
                                  {'word': 'KUNDUZ', 'hint': 'Baraj yapabilen kemirgen'},
                                  {'word': 'SİNCAP', 'hint': 'Ağaçta yaşayan, fındık toplayan hayvan'},
                                  {'word': 'JAGUAR', 'hint': "Güney Amerika'nın benekli yırtıcısı"},
                                  {'word': 'LEOPAR', 'hint': "Afrika'da benekli büyük kedi"},
                                  {'word': 'SANSAR', 'hint': 'Gece avlanan, kürkü değerli hayvan'}],
                              7: [{'word': 'OKYANUS', 'hint': 'Dünyanın en büyük su kütlesi'},
                                  {'word': 'HABİTAT', 'hint': 'Bir canlının doğal yaşam alanı'},
                                  {'word': 'KASIRGA', 'hint': 'Tropik siklonun şiddetli hali'},
                                  {'word': 'KURAKLI', 'hint': 'Uzun süre yağmur görmeme hali'},
                                  {'word': 'YILDIRI', 'hint': 'Gökyüzünden inen elektrik boşalması'},
                                  {'word': 'TSUNAMİ', 'hint': 'Deprem sonrası okyanusta yükselen dev dalga'}],
                              8: [{'word': 'FLAMINGO', 'hint': 'Pembe tüylü, tek ayakta duran kuş'},
                                  {'word': 'ATMOSFER', 'hint': 'Yeryüzünü saran gaz tabakası'},
                                  {'word': 'YILDIRIM', 'hint': 'Gökyüzünden inen elektrik boşalması'},
                                  {'word': 'ORANGUTA', 'hint': 'Borneo ormanlarında yaşayan primat'},
                                  {'word': 'MANTARCI', 'hint': 'Mantar toplayan veya yetiştiren kişi'},
                                  {'word': 'VOLKANIK', 'hint': 'Volkanlaşmayla ilgili süreç'}],
                              9: [{'word': 'ORANGUTAN', 'hint': 'Borneo ormanlarında yaşayan primat'},
                                  {'word': 'MANTARLIK', 'hint': 'Mantarların doğal olarak yetiştiği alan'},
                                  {'word': 'FOTOPLANK', 'hint': 'Denizde fotosentez yapan mikroskobik canlı'},
                                  {'word': 'OKSİJENLİ', 'hint': 'Solunum için gerekli gazı içeren'},
                                  {'word': 'HEYELANLI', 'hint': 'Toprak kaymasına yatkın arazi'},
                                  {'word': 'MİKROPLAN', 'hint': 'Görünmez canlıların kolonisi'}]},
          'bonus': [{'word': 'FOTOSENTEZ', 'hint': 'Bitkilerin güneş ışığıyla besin üretmesi'},
                    {'word': 'BİYOÇEŞİTLİLİK', 'hint': 'Bir ekosistemdeki tür zenginliği'},
                    {'word': 'MİKROORGANİZMA', 'hint': 'Çıplak gözle görülemeyen canlı'},
                    {'word': 'KARBONAYAKİZİ', 'hint': 'Fosil yakıt tüketiminin çevresel etkisi'},
                    {'word': 'OKSİJENKONSANTRASYONU', 'hint': 'Atmosferdeki O₂ oranı'}]},
 'kavram': {'label': 'Kavram',
            'description': 'Felsefe, mantık ve soyut düşünce',
            'words_by_length': {3: [{'word': 'AKL', 'hint': "Descartes'in kuşkulanmadığı tek şey"},
                                    {'word': 'VAR', 'hint': "Heidegger'in sorguladığı temel kavram"},
                                    {'word': 'YOK', 'hint': 'Hiçlik felsefesinin konusu'},
                                    {'word': 'NEF', 'hint': "Platon'un ideal form düşüncesi"},
                                    {'word': 'İDE', 'hint': "Platon'un idealar dünyasındaki birim"},
                                    {'word': 'GER', 'hint': 'Gerçekliğin özüne işaret eden kısaltma'}],
                                4: [{'word': 'ÖZDE', 'hint': 'Bir şeyin değişmeyen doğası'},
                                    {'word': 'DİLE', 'hint': 'Dilek ve arzu bildiren sözcük'},
                                    {'word': 'AMAÇ', 'hint': "Aristoteles'in telos kavramı"},
                                    {'word': 'NİYE', 'hint': 'Neden sorusunun kısaltılmış hali'},
                                    {'word': 'KANT', 'hint': 'Saf aklın eleştirisinin yazarı'},
                                    {'word': 'AKIL', 'hint': 'Muhakeme ve düşünme yetisi'}],
                                5: [{'word': 'ÖZGÜR', 'hint': "Kant'ın sorduğu irade hali"},
                                    {'word': 'İSPAT', 'hint': 'Tezi doğrulayan mantıksal kanıt'},
                                    {'word': 'ÖNERM', 'hint': 'Doğru veya yanlış olabilen ifade'},
                                    {'word': 'TEORİ', 'hint': 'Gözlemleri açıklayan düşünce sistemi'},
                                    {'word': 'DEİZM', 'hint': "Tanrı'ya inanıp vahye şüphe duyan görüş"},
                                    {'word': 'TEZİS', 'hint': 'Savunulan ana düşünce'}],
                                6: [{'word': 'MEDENİ', 'hint': 'Uygar toplum düzenine ait'},
                                    {'word': 'DİALET', 'hint': 'Tez antitez sentez yöntemi'},
                                    {'word': 'ÖNERGE', 'hint': 'Meclise sunulan yasa taslağı'},
                                    {'word': 'KANTÇI', 'hint': 'Saf aklın eleştirisi okuluna mensup'},
                                    {'word': 'SOKRAT', 'hint': 'Sorgulama yönteminin kurucusu'},
                                    {'word': 'ÖZGÜRL', 'hint': 'Özgür olma durumunun kökü'}],
                                7: [{'word': 'FELSEFE', 'hint': "Bilgelik sevgisi, Sokrates'in alanı"},
                                    {'word': 'PARADOK', 'hint': 'Çelişkili görünen ama doğru olabilen önerme'},
                                    {'word': 'DİALETİ', 'hint': 'Tez antitez sentez yöntemi'},
                                    {'word': 'UTILİTE', 'hint': 'Faydacılığın ölçtüğü değer'},
                                    {'word': 'ONTOLOJ', 'hint': 'Varlığın doğasını inceleyen dal'},
                                    {'word': 'EPİSTEM', 'hint': 'Bilgi kuramının kök kavramı'}],
                                8: [{'word': 'NİHİLİZM', 'hint': 'Hiçbir değerin mutlak olmadığı akım'},
                                    {'word': 'UTILİTAR', 'hint': 'En çok sayıya en çok mutluluk ilkesi'},
                                    {'word': 'ONTOLOJİ', 'hint': 'Varlığın doğasını inceleyen dal'},
                                    {'word': 'DETERMİN', 'hint': 'Her olayın nedeni olduğu görüş'},
                                    {'word': 'HERMENEU', 'hint': 'Metin yorumlama sanatının kökü'},
                                    {'word': 'METAFİZİ', 'hint': 'Varlığın ötesini sorgulayan felsefe'}],
                                9: [{'word': 'METAFİZİK', 'hint': 'Varlığın ötesini sorgulayan felsefe dalı'},
                                    {'word': 'POSTMODER', 'hint': 'Büyük anlatıları reddeden akım'},
                                    {'word': 'DETERMİST', 'hint': 'Her olayın nedeni olduğuna inanan'},
                                    {'word': 'VAROLUŞCU', 'hint': "Sartre'ın temsil ettiği felsefi akım"},
                                    {'word': 'FAYDACILI', 'hint': 'En büyük faydayı hedefleyen etik görüş'},
                                    {'word': 'ONTOLOJİK', 'hint': 'Varlık sorunlarıyla ilgili'}]},
            'bonus': [{'word': 'EXISTANSİYALİZM', 'hint': "Sartre'ın varoluşçu felsefesi"},
                      {'word': 'POSTMODERNİZM', 'hint': 'Büyük anlatıları reddeden akım'},
                      {'word': 'TRANSCENDENTAL', 'hint': "Kant'ın deney ötesi sorgulaması"},
                      {'word': 'HERMENEUTİK', 'hint': 'Metin yorumlama sanatı'},
                      {'word': 'UTILITARIANISM', 'hint': 'Faydacılık felsefesinin İngilizce adı'},
                      {'word': 'FENOMENOLOJİ', 'hint': 'Özdeneyimin incelendiği felsefe'}]}}
